name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
      
    - name: Archive artifacts 
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: Geyser Fabric
        path: target/release/apex-tux
        if-no-files-found: error
